// <auto-generated />
using System;
using LondonStockExchange.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LondonStockExchange.Infrastructure.Migrations
{
    [DbContext(typeof(LondonStockDbContext))]
    [Migration("20260115170439_NewChanges")]
    partial class NewChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LondonStockExchange.Domain.Entities.StockPriceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long>("TradeCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("StockPriceSnapshots", (string)null);
                });

            modelBuilder.Entity("LondonStockExchange.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrokerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("LondonStockExchange.Domain.Entities.StockPriceSnapshot", b =>
                {
                    b.OwnsOne("LondonStockExchange.Domain.ValueObjects.TickerSymbol", "TickerSymbol", b1 =>
                        {
                            b1.Property<Guid>("StockPriceSnapshotId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("TickerSymbol");

                            b1.HasKey("StockPriceSnapshotId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("StockPriceSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("StockPriceSnapshotId");
                        });

                    b.Navigation("TickerSymbol")
                        .IsRequired();
                });

            modelBuilder.Entity("LondonStockExchange.Domain.Entities.Trade", b =>
                {
                    b.OwnsOne("LondonStockExchange.Domain.ValueObjects.TickerSymbol", "TickerSymbol", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("TickerSymbol");

                            b1.HasKey("TradeId");

                            b1.HasIndex("Value");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.Navigation("TickerSymbol")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
